USE [ipeds]
GO

/****** Object:  Table [dbo].[Institutions]    Script Date: 5/14/2015 3:53:12 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Institutions](
	[Unitid] [int] NOT NULL,
	[InstitutionName] [nvarchar](100) NOT NULL,
	[InstitutionShortName] [nvarchar](100) NULL CONSTRAINT [DF__Instituti__Insti__108B795B]  DEFAULT (NULL),
	[Address] [nvarchar](100) NULL CONSTRAINT [DF__Instituti__Addre__117F9D94]  DEFAULT (NULL),
	[City] [nvarchar](255) NULL CONSTRAINT [DF__Institutio__City__1273C1CD]  DEFAULT (NULL),
	[StateAbbreviation] [nchar](2) NULL CONSTRAINT [DF__Instituti__State__1367E606]  DEFAULT (NULL),
	[State] [nvarchar](32) NULL CONSTRAINT [DF__Instituti__State__145C0A3F]  DEFAULT (NULL),
	[ZIP] [nchar](10) NULL CONSTRAINT [DF__Institution__ZIP__15502E78]  DEFAULT (NULL),
	[FIPS] [smallint] NULL CONSTRAINT [DF__Institutio__FIPS__164452B1]  DEFAULT (NULL),
	[RegionCode] [smallint] NULL CONSTRAINT [DF__Instituti__Regio__173876EA]  DEFAULT (NULL),
	[RegionLiteral] [nvarchar](64) NULL CONSTRAINT [DF__Instituti__Regio__182C9B23]  DEFAULT (NULL),
	[EIN] [nchar](9) NULL CONSTRAINT [DF__Institution__EIN__1920BF5C]  DEFAULT (NULL),
	[OpeId] [nchar](9) NULL CONSTRAINT [DF__Instituti__OpeId__1A14E395]  DEFAULT (NULL),
	[OpeStatusCode] [smallint] NOT NULL CONSTRAINT [DF__Instituti__OpeSt__1B0907CE]  DEFAULT ('-1'),
	[OpeStatusLiteral] [nvarchar](68) NULL CONSTRAINT [DF__Instituti__OpeSt__1BFD2C07]  DEFAULT (NULL),
	[SectorCode] [smallint] NOT NULL,
	[SectorLiteral] [nvarchar](40) NULL CONSTRAINT [DF__Instituti__Secto__1CF15040]  DEFAULT (NULL),
	[LevelCode] [smallint] NOT NULL,
	[LevelLiteral] [nvarchar](35) NULL CONSTRAINT [DF__Instituti__Level__1DE57479]  DEFAULT (NULL),
	[ControlCode] [smallint] NOT NULL,
	[ControlLiteral] [nvarchar](32) NULL CONSTRAINT [DF__Instituti__Contr__1ED998B2]  DEFAULT (NULL),
	[HighestLevelOfferingCode] [smallint] NULL CONSTRAINT [DF__Instituti__Highe__1FCDBCEB]  DEFAULT (NULL),
	[HighestLevelOfferingLiteral] [nvarchar](40) NULL CONSTRAINT [DF__Instituti__Highe__20C1E124]  DEFAULT (NULL),
	[HighestDegreeOfferingCode] [smallint] NULL CONSTRAINT [DF__Instituti__Highe__21B6055D]  DEFAULT (NULL),
	[HighestDegreeOfferingLiteral] [nvarchar](64) NULL CONSTRAINT [DF__Instituti__Highe__22AA2996]  DEFAULT (NULL),
	[LocaleCode] [smallint] NULL CONSTRAINT [DF__Instituti__Local__239E4DCF]  DEFAULT (NULL),
	[LocaleLiteral] [nvarchar](64) NULL CONSTRAINT [DF__Instituti__Local__24927208]  DEFAULT (NULL),
	[RollupUnitid] [int] NULL CONSTRAINT [DF__Instituti__Rollu__25869641]  DEFAULT (NULL),
	[DeathYear] [smallint] NULL CONSTRAINT [DF__Instituti__Death__267ABA7A]  DEFAULT (NULL),
	[CloseDate] [nvarchar](16) NULL CONSTRAINT [DF__Instituti__Close__276EDEB3]  DEFAULT (NULL),
	[CarnegieBasic2010Code] [smallint] NOT NULL CONSTRAINT [DF__Instituti__Carne__286302EC]  DEFAULT ('0'),
	[CarnegieBasic2010Literal] [nvarchar](104) NULL CONSTRAINT [DF__Instituti__Carne__29572725]  DEFAULT (NULL),
	[CarnegieUndergraduateInstructionalProgram2010Code] [smallint] NOT NULL CONSTRAINT [DF__Instituti__Carne__2A4B4B5E]  DEFAULT ('0'),
	[CarnegieUndergraduateInstructionalProgram2010Literal] [nvarchar](73) NULL CONSTRAINT [DF__Instituti__Carne__2B3F6F97]  DEFAULT (NULL),
	[CarnegieGraduateInstructionalProgram2010Code] [smallint] NOT NULL CONSTRAINT [DF__Instituti__Carne__2C3393D0]  DEFAULT ('0'),
	[CarnegieGraduateInstructionalProgram2010Literal] [nvarchar](81) NULL CONSTRAINT [DF__Instituti__Carne__2D27B809]  DEFAULT (NULL),
	[CarnegieUndergraduateProfile2010Code] [smallint] NOT NULL CONSTRAINT [DF__Instituti__Carne__2E1BDC42]  DEFAULT ('0'),
	[CarnegieUndergraduateProfile2010Literal] [nvarchar](69) NULL CONSTRAINT [DF__Instituti__Carne__2F10007B]  DEFAULT (NULL),
	[CarnegieEnrollmentProfile2010Code] [smallint] NOT NULL CONSTRAINT [DF__Instituti__Carne__300424B4]  DEFAULT ('0'),
	[CarnegieEnrollmentProfile2010Literal] [nvarchar](41) NULL CONSTRAINT [DF__Instituti__Carne__30F848ED]  DEFAULT (NULL),
	[CarnegieSizeSetting2010Code] [smallint] NOT NULL CONSTRAINT [DF__Instituti__Carne__31EC6D26]  DEFAULT ('0'),
	[CarnegieSizeSetting2010Literal] [nvarchar](54) NULL CONSTRAINT [DF__Instituti__Carne__32E0915F]  DEFAULT (NULL),
	[CarnegieCommunityEngagement2010Code] [smallint] NOT NULL CONSTRAINT [DF__Instituti__Carne__33D4B598]  DEFAULT ('0'),
	[CarnegieCommunityEngagement2010Literal] [nvarchar](49) NULL CONSTRAINT [DF__Instituti__Carne__34C8D9D1]  DEFAULT (NULL),
	[Carnegie1987Code] [smallint] NULL CONSTRAINT [DF__Instituti__Carne__35BCFE0A]  DEFAULT (NULL),
	[Carnegie1987Literal] [nvarchar](25) NULL CONSTRAINT [DF__Instituti__Carne__36B12243]  DEFAULT (NULL),
	[Carnegie1994Code] [smallint] NULL CONSTRAINT [DF__Instituti__Carne__37A5467C]  DEFAULT (NULL),
	[Carnegie1994Literal] [nvarchar](34) NULL CONSTRAINT [DF__Instituti__Carne__38996AB5]  DEFAULT (NULL),
	[Carnegie2000Code] [smallint] NULL CONSTRAINT [DF__Instituti__Carne__398D8EEE]  DEFAULT (NULL),
	[Carnegie2000Literal] [nvarchar](97) NULL CONSTRAINT [DF__Instituti__Carne__3A81B327]  DEFAULT (NULL),
	[Carnegie2005Code] [smallint] NULL CONSTRAINT [DF__Instituti__Carne__3B75D760]  DEFAULT ('-1'),
	[Carnegie2005Literal] [nvarchar](120) NULL CONSTRAINT [DF__Instituti__Carne__3C69FB99]  DEFAULT (NULL),
	[InstitutionSizeCode] [smallint] NULL CONSTRAINT [DF__Instituti__Insti__3D5E1FD2]  DEFAULT (NULL),
	[InstitutionSizeLiteral] [nvarchar](64) NULL CONSTRAINT [DF__Instituti__Insti__3E52440B]  DEFAULT (NULL),
	[CbsaCode] [int] NULL CONSTRAINT [DF__Instituti__CbsaC__3F466844]  DEFAULT (NULL),
	[CbsaLiteral] [nvarchar](50) NULL CONSTRAINT [DF__Instituti__CbsaL__403A8C7D]  DEFAULT (NULL),
	[CbsaTypeCode] [int] NULL CONSTRAINT [DF__Instituti__CbsaT__412EB0B6]  DEFAULT (NULL),
	[CbsaTypeLiteral] [nvarchar](29) NULL CONSTRAINT [DF__Instituti__CbsaT__4222D4EF]  DEFAULT (NULL),
	[CsaCode] [int] NULL CONSTRAINT [DF__Instituti__CsaCo__4316F928]  DEFAULT (NULL),
	[CsaLiteral] [nvarchar](61) NULL CONSTRAINT [DF__Instituti__CsaLi__440B1D61]  DEFAULT (NULL),
	[NectaCode] [int] NULL CONSTRAINT [DF__Instituti__Necta__44FF419A]  DEFAULT (NULL),
	[NectaLiteral] [nvarchar](40) NULL CONSTRAINT [DF__Instituti__Necta__45F365D3]  DEFAULT (NULL),
	[CountyFips] [int] NULL CONSTRAINT [DF__Instituti__Count__46E78A0C]  DEFAULT (NULL),
	[CountyName] [nvarchar](64) NULL CONSTRAINT [DF__Instituti__Count__47DBAE45]  DEFAULT (NULL),
	[Longitude] [decimal](16, 10) NULL CONSTRAINT [DF__Instituti__Longi__48CFD27E]  DEFAULT (NULL),
	[Latitude] [decimal](16, 10) NULL CONSTRAINT [DF__Instituti__Latit__49C3F6B7]  DEFAULT (NULL),
	[StandardComparisonGroupCode] [smallint] NOT NULL CONSTRAINT [DF__Instituti__Stand__4AB81AF0]  DEFAULT ('-1'),
	[StandardComparisonGroupLiteral] [nvarchar](64) NULL CONSTRAINT [DF__Instituti__Stand__4BAC3F29]  DEFAULT (NULL),
	[ExpandedComparisonGroupCode] [smallint] NOT NULL CONSTRAINT [DF__Instituti__Expan__4CA06362]  DEFAULT ('-1'),
	[ExpandedComparisonGroupLiteral] [nvarchar](64) NULL CONSTRAINT [DF__Instituti__Expan__4D94879B]  DEFAULT (NULL),
	[MultiCampusSystemLiteral] [nvarchar](64) NULL CONSTRAINT [DF__Instituti__Multi__4E88ABD4]  DEFAULT (NULL),
	[IsUndergraduateOffering] [bit] NOT NULL,
	[IsGraduateOffering] [bit] NOT NULL,
	[IsAllInstitutions] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsAll__4F7CD00D]  DEFAULT ((0)),
	[IsAau] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsAau__5070F446]  DEFAULT ((0)),
	[IsAauAspirant] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsAau__5165187F]  DEFAULT ((0)),
	[IsAauPrivate] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsAau__52593CB8]  DEFAULT ((0)),
	[IsAauPublic] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsAau__534D60F1]  DEFAULT ((0)),
	[IsAauPrivateMedical] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsAau__5441852A]  DEFAULT ((0)),
	[IsAauPrivateNoMedical] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsAau__5535A963]  DEFAULT ((0)),
	[IsDegreeGranting] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsDeg__5629CD9C]  DEFAULT ((0)),
	[IsSystemMember] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsSys__571DF1D5]  DEFAULT ((0)),
	[IsPrivate] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsPri__5812160E]  DEFAULT ((0)),
	[IsPnp] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsPnp__59063A47]  DEFAULT ((0)),
	[IsPublic] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsPub__59FA5E80]  DEFAULT ((0)),
	[IsNonProfit] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsNon__5AEE82B9]  DEFAULT ((0)),
	[IsOpenPublic] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsOpe__5BE2A6F2]  DEFAULT ((0)),
	[IsCatholic] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsCat__5CD6CB2B]  DEFAULT ((0)),
	[IsReligious] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsRel__5DCAEF64]  DEFAULT ((0)),
	[IsLandGrant] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsLan__5EBF139D]  DEFAULT ((0)),
	[IsHbcu] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsHbc__5FB337D6]  DEFAULT ((0)),
	[IsClosed] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsClo__60A75C0F]  DEFAULT ((0)),
	[IsOpe] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsOpe__619B8048]  DEFAULT ((0)),
	[IsHospital] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsHos__628FA481]  DEFAULT ((0)),
	[IsMedical] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsMed__6383C8BA]  DEFAULT ((0)),
	[IsTribal] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsTri__6477ECF3]  DEFAULT ((0)),
	[IsCofhe] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsCof__656C112C]  DEFAULT ((0)),
	[IsColonialGroup] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsCol__66603565]  DEFAULT ((0)),
	[IsRotc] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsRot__6754599E]  DEFAULT ((0)),
	[IsR1] [bit] NOT NULL CONSTRAINT [DF__Institutio__IsR1__68487DD7]  DEFAULT ((0)),
	[IsR2] [bit] NOT NULL CONSTRAINT [DF__Institutio__IsR2__693CA210]  DEFAULT ((0)),
	[IsDru] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsDru__6A30C649]  DEFAULT ((0)),
	[IsAcc] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsAcc__6B24EA82]  DEFAULT ((0)),
	[IsBigTen] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsBig__6C190EBB]  DEFAULT ((0)),
	[IsBigEast] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsBig__6D0D32F4]  DEFAULT ((0)),
	[IsBig12] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsBig__6E01572D]  DEFAULT ((0)),
	[IsPac12] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsPac__6EF57B66]  DEFAULT ((0)),
	[IsSec] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsSec__6FE99F9F]  DEFAULT ((0)),
	[IsPowerFive] [bit] NOT NULL CONSTRAINT [DF__Instituti__IsPow__70DDC3D8]  DEFAULT ((0)),
	[IsWomen] [bit] NOT NULL CONSTRAINT [DF_Institutions_IsWomen]  DEFAULT ((0)),
	[IsUrban] [bit] NOT NULL CONSTRAINT [DF_Institutions_IsUrban]  DEFAULT ((0)),
	[IsND] [bit] NOT NULL CONSTRAINT [DF__Institutio__IsND__71D1E811]  DEFAULT ((0)),
 CONSTRAINT [PK__Institut__44F6E08D6910A04F] PRIMARY KEY CLUSTERED 
(
	[Unitid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


